# 使用方式：- uses: ./.github/actions/setup-node
name: "配置 Node.js"
description: "为 CI 设置 Node.js"
inputs:
  node-version:
    description: "要安装的节点版本"
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"

    - name: 开启 corepack
      shell: bash
      run: corepack enable

    - name: 安装依赖
      shell: bash
      run: yarn
