[package]
name = "cli"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
clap = { workspace = true, features = ["cargo","derive"] }
indoc = { workspace = true }
anyhow = { workspace = true }
