# workaround for getting workspace root dir, reference: https://github.com/rust-lang/cargo/issues/3946
[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
lint = "clippy --workspace --all-targets -- --deny warnings"
# AKA `test-update`, handy cargo rst update without install `cargo-rst` binary
t = "test --no-fail-fast"

# target-feature=+crt-static 是 Rust 编译器的一个选项，用于指定目标应使用静态链接的 C 运行时库 (CRT)
# 这意味着 C 运行时库将直接包含在二进制文件中，而不是在运行时依赖系统的动态库。
[target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "target-feature=+crt-static"]
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static", "-Zshare-generics=y"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static", "-C", "link-arg=-lgcc"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse2"]

# https://doc.rust-lang.org/rustc/codegen-options/index.html#linker
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
