[env]
# CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
# bump     = "run --package swc-releaser -- bump"

[build]
# rustdocflags = ["--cfg", "docsrs"]
# rustflags    = ["-Zshare-generics=y"]
