# workaround for getting workspace root dir, reference: https://github.com/rust-lang/cargo/issues/3946
[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
lint = "clippy --workspace --all-targets -- --deny warnings"
# AKA `test-update`, handy cargo rst update without install `cargo-rst` binary
t = "test --no-fail-fast"

[target.'cfg(all())']
rustflags = [
    # CLIPPY LINT SETTINGS
    # This is a workaround to configure lints for the entire workspace, pending the ability to configure this via TOML.
    # See: `https://github.com/rust-lang/cargo/issues/5034`
    #      `https://github.com/EmbarkStudios/rust-ecosystem/issues/22#issuecomment-947011395`
    "-Wclippy::all", # all lints that are on by default (correctness, suspicious, style, complexity, perf)
    # restriction
    "-Wclippy::dbg_macro",
    # Disable this as semantics of `expect` and `Result` are different.
    # See: `https://github.com/web-infra-dev/rspack/pull/4848`
    # "-Wclippy::unwrap_in_result",
    "-Wclippy::unwrap_used",
    "-Wclippy::empty_drop",
    "-Wclippy::exit",
    "-Wclippy::empty_structs_with_brackets",
    "-Wclippy::rc_buffer",
    "-Wclippy::rc_mutex",
    "-Wclippy::same_name_method",
    #
    "-Aclippy::default_constructed_unit_structs",
    "-C",
    "symbol-mangling-version=v0",
]

# 修复了测试环境中的 napi 中断问题 <https://github.com/napi-rs/napi-rs/issues/1005#issuecomment-1011034770>
# 为了能够在 macOS 上运行单元测试，支持编译为“x86_64-apple-darwin”。
[target.'cfg(target_vendor = "apple")']
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup,-no_fixup_chains"]

# 为了能够在 Linux 上运行单元测试，支持编译到“x86_64-unknown-linux-gnu”
[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-args=-Wl,--warn-unresolved-symbols"]

# 为了能够在 Windows 上运行单元测试，支持编译为“x86_64-pc-windows-msvc”。
[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/FORCE"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# 修复 Github Actions Napi 中 zig: not found 问题
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["-C", "target-feature=-crt-static"]