/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare export declare function compress(file: string, options: object): CompressInfo

export interface CompressInfo {
  ext: Kind
  beforeSize: bigint
  afterSize: bigint
  rate: number
  compressedImage: Buffer
}

export declare export declare function initCustomTraceSubscriber(traceOutFilePath?: string | undefined | null): void

export declare const enum Kind {
  jpeg = 'jpeg',
  png = 'png',
  gif = 'gif',
  webp = 'webp',
  avif = 'avif',
  unknown = 'unknown'
}

