/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function asyncFib(input: number): Promise<string>

/**
 * ## 调用后结果
 * \[0\] \[1\] ..
 *
 * ts_args_type: 强制指定参数类型
 */
export declare function callThreadsafeFunction(callback: (err: null | Error, result: number) => void): void

export const DEFAULT_COST: number

export declare function getPaths(pattern: string, path: string, maxDeep: number): string[]

export declare function initCustomTraceSubscriber(traceOutFilePath?: string | undefined | null): void

export declare function readFile(path: string, callback: ((err: Error | null, arg: Error | string) => unknown)): void

