name: Single Docker build

description: Docker build for a single target

inputs:
  target:
    description: "构建的目标"
    required: true

  image:
    description: "Docker 镜像名称"
    required: true

  profile:
    description: "编译模式"
    default: "release"
    required: false

  options:
    description: "Docker 镜像选项"
    default: ""
    required: false

  pre:
    required: false
    default: ""
    description: "构建前执行的命令"

  post:
    required: false
    default: ""
    description: "构建后执行的命令"

runs:
  using: composite
  steps:
    - name: Docker Build ${{ inputs.target }}
      shell: bash
      run: |
        code='
          set -e
          ${{ inputs.pre }}
          rustup target add ${{ inputs.target }}

          # corepack > 0.24.1 will use native fetch
          # and native fetch not support HTTP_PROXY
          # https://github.com/nodejs/undici/issues/1650
          npm install -g corepack@0.24.1
          corepack enable

          cd packages &&
          RUST_TARGET=${{ inputs.target }} pnpm build:node-dev --target ${{ matrix.settings.target }}
          ${{ inputs.post }}
        '


        if [[ ! -n "$CARGO_HOME" ]]; then
          CARGO_HOME="$(dirname $(dirname $(which cargo)))"
        fi


        docker run \
          --rm \
          --privileged \

          # --user 0:0 用于指定在容器内运行进程的用户和用户组。0:0 表示使用 root 用户和 root 用户组。
          --user 0:0 \

          # -v 代表挂载目（冒号左侧）录到容器（冒号右侧）指定目录下
          -v ${{ github.workspace }}/.cargo-cache/.cargo/git:/usr/local/cargo/git \
          -v ${{ github.workspace }}/.cargo-cache/.cargo/registry:/usr/local/cargo/registry \
          ${{ inputs.options }} \

          # -e 用于设置环境变量
          -e CI=1 \
          -e HOME=$HOME \

          -v $HOME/.cache:$HOME/.cache \
          -v ${{ github.workspace }}:/build \

          # -w 用于指定工作目录在容器哪个目录下
          -w /build \

          -i \
          ${{ inputs.image }} \

          # 使用 bash shell 执行代码 -c ：是一个选项，指示后面跟随的是要执行的命令字符串。
          bash -c "$code"
