[package]
name = "binding_node"
build = "build.rs"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
image_compress = { path = "../../crates/image-compress", features = ["native"] }
utils = { path = "../../crates/utils", features = ["hook"] }

tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing-futures.workspace = true
tracing-chrome.workspace = true

chrono.workspace = true

napi.workspace = true
napi-derive.workspace = true
backtrace.workspace = true
once_cell.workspace = true


[build-dependencies]
napi-build.workspace = true
