[package]
name = "binding_node"
build = "build.rs"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
utils = { path = "../utils", features = ["hook"] }
image_compress.workspace = true

tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing-futures.workspace = true
tracing-chrome.workspace = true

chrono.workspace = true

backtrace.workspace = true
once_cell.workspace = true

napi = { version = "3.9.0", features = [
  "napi9",
  "async",
  "serde-json",
  "chrono_date",
] }
napi-derive = { git = "https://github.com/napi-rs/napi-rs.git", features = [
  "type-def",
], branch = "main" }


[build-dependencies]
napi-build = "2.3.2"
