# 其他参考文：
# https://github.com/biomejs/biome/blob/main/.github/workflows/release_cli.yml
# https://github.com/orhun/git-cliff/blob/main/.github/workflows/cd.yml
# https://github.com/skyra-project/ai/actions/runs/5556591465/workflow?pr=131
# https://github.com/napi-rs/node-rs/actions/runs/5606629914/workflow

name: "构建 Cargo 包"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_RELEASE_LTO: "fat"
  GIT_AUTHOR_NAME: "SWC Bot"
  GIT_AUTHOR_EMAIL: "bot@swc.rs"
  GIT_COMMITTER_NAME: "SWC Bot"
  GIT_COMMITTER_EMAIL: "bot@swc.rs"

permissions:
  contents: write
  id-token: write

on:
  # 工作流的执行依赖其他 workflow 的调用
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      version:
        type: string
        required: true
      buildCli:
        type: boolean
        required: true
      skipBuild:
        type: boolean
        required: true
      skipPublishing:
        type: boolean
        required: true
      profile:
        type: string
        required: false
        default: release

jobs:
  check-if-build-required:
    name: 是否需要构建
    runs-on: ubuntu-latest
    outputs:
      need-build: ${{ steps.check.outputs.need-build }}
    steps:
      - uses: actions/checkout@v4
      # TODO: 检查是否存在 artifacts
      - id: check
        if: ${{ !inputs.skipBuild }}
        run: |
          echo "need-build=true" >> $GITHUB_OUTPUT

  create-git-tag-commit:
    name: 创建 Git Tag 提交日志
    runs-on: ubuntu-latest
    needs:
      - check-if-build-required
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "master"

      - uses: ./.github/actions/setup-node

      - name: 安装 git-cliff 准备获取 changelog
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@1.3.1

      - name: 安装 cargo-edit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit@0.12.2

      - name: "设置 jq 轻量级的命令行 JSON 处理工具"
        uses: dcarbone/install-jq-action@v2
        with:
          version: "1.7"
          force: true

    # 获取 determine-nightly-version 的 version 通过 ssh 生成 git tag 后，在后边使用
    #   - uses: webfactory/ssh-agent@v0.9.0
    #     if: needs.check-if-build-required.outputs.need-build == 'true' && !inputs.skipPublishing
    #     with:
    #       ssh-private-key: ${{ secrets.SWC_BOT_SSH }}

    #   - name: Create git tag commit
    #     if: needs.check-if-build-required.outputs.need-build == 'true' && !inputs.skipPublishing
    #     run: |
    #       ./scripts/publish.sh ${{ inputs.version }}

  build:
    if: needs.check-if-build-required.outputs.need-build == 'true'
    needs:
      - check-if-build-required
      - create-git-tag-commit
    strategy:
      fail-fast: false
      matrix:
        settings:
          # - host: macos-latest
          #   target: x86_64-apple-darwin
          #   build: |
          #     cd packages && pnpm build:node-dev --target x86_64-apple-darwin
          #     strip -x ./dist/node/*.node

          # - host: macos-latest
          #   target: aarch64-apple-darwin
          #   build: |
          #     sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*;
          #     export CC=$(xcrun -f clang);
          #     export CXX=$(xcrun -f clang++);
          #     SYSROOT=$(xcrun --sdk macosx --show-sdk-path);
          #     export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";
          #     cd packages &&
          #     pnpm build:node-dev --target aarch64-apple-darwin

          # - host: windows-latest
          #   target: x86_64-pc-windows-msvc
          #   build: |
          #     cd packages && pnpm build:node-dev --target x86_64-pc-windows-msvc

          # - host: windows-latest
          #   target: i686-pc-windows-msvc
          #   build: |
          #     cd packages && pnpm build:node-dev --target i686-pc-windows-msvc

          # - host: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   build: |
          #     cd packages && pnpm build:node-dev --target aarch64-pc-windows-msvc

          # - host: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
          #   build: >-
          # - host: ubuntu-latest
          #   target: x86_64-unknown-linux-musl
          #   docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
          #   build: >-
          # - host: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          #   docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
          #   build: >-
          # - host: ubuntu-latest
          #   target: aarch64-unknown-linux-musl
          #   docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
          #   build: >-
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            setup: |
              sudo apt-get update
              sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y
              sudo apt install ninja-build meson nasm
              sudo apt-get -y install clang llvm
            build: |
              cargo build -p test --release --target armv7-unknown-linux-gnueabihf --verbose
            #              cd packages && pnpm build:node-dev --target armv7-unknown-linux-gnueabihf

    name: "构建 ${{ inputs.package }} - ${{ matrix.settings.target }} - node@20"
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
        # 引用 git tag 版本
        # with:
        #   ref: "v${{ inputs.version }}"

      - name: 开启 Node Corepack
        shell: bash
        run: corepack enable

      - name: 设置 Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          architecture: x64

      - name: 获取 rust toolchain 版本号
        id: toolchain
        shell: bash
        run: echo "version=$(cat ./rust-toolchain)" >> "$GITHUB_OUTPUT"

      - name: 安装 rust toolchain
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          targets: ${{ matrix.settings.target }}
          toolchain: stable
          # toolchain: ${{ steps.toolchain.outputs.version }}

      - name: 缓存 cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            .cargo-cache
          key: ${{ matrix.settings.target }}-cargo-registry

      - name: 设置 toolchain 依赖的环境
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash

        # 在 Github Actions 工作流程中使用 Zig 编译器
      - uses: goto-bus-stop/setup-zig@v2
        # if: ${{ contains(matrix.settings.target,'linux') }}
        if: ${{ matrix.settings.target == 'armv7-unknown-linux-gnueabihf' }}
        with:
          version: 0.13.0

      - name: 安装依赖
        shell: bash
        run: |
          corepack enable
          pnpm install
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          echo '/usr/local/cargo/bin' >> $GITHUB_PATH

      - name: 在 Docker 中构建
        if: ${{ matrix.settings.docker }}
        uses: ./.github/actions/docker-build
        with:
          image: ${{ matrix.settings.docker }}
          post: ${{ matrix.settings.build }}
          target: ${{ matrix.settings.target }}

      - name: 普通构建
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash

      # - name: 展示 packages
      #   working-directory: ./
      #   run: |
      #     mkdir tag
      #     cp -r ./packages/dist/node/* ./tag
      #     chmod +x ./tag
      #     ls -R ./tag
      #   shell: bash

      - name: 上传 artifact
        uses: actions/upload-artifact@v4
        with:
          # 上传归档的名称
          name: bindings-${{ matrix.settings.target }}
          # 归档的文件路径 xx* 代表以 xx 开头的文件
          path: |
            ./packages/dist/node/image-compress*
          if-no-files-found: error

  publish:
    needs: build
    name: 发布 ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        # ref: "v${{ inputs.version }}"

      - uses: ./.github/actions/setup-node

      - name: 设置 npm 发行版标签
        run: |
          if [[ '${{ inputs.version }}' != *"nightly"* ]]; then
            echo "NPM_TAG=latest" >> $GITHUB_ENV
          else
            echo "NPM_TAG=nightly" >> $GITHUB_ENV
          fi

      - name: 安装依赖
        run: corepack enable && pnpm install

      - name: 下载所有 artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./packages/artifacts

      - name: 展示 artifacts 文件
        run: ls -R ./packages/artifacts
        shell: bash

      - name: 重命名 artifacts 文件
        run: |
          cp -r -v ./packages/artifacts/**/*.node ./packages/artifacts
        shell: bash

      #     - name: 移动 artifacts 文件
      #       shell: bash
      #       working-directory: .
      #       run: |
      #         chmod +x ./.github/scripts/cli_artifacts_rename.sh
      #         ./.github/scripts/cli_artifacts_rename.sh

      # - name: 设置 npm 包依赖
      #   shell: bash
      #   run: |
      #     node ./scripts/update_fallback_dependencies.js

      # - name: 发布 npm 包及长传 .node 文件到 github release
      # npm config set provenance true 命令设置发布 npm 包时候自动发布 github release https://docs.npmjs.com/generating-provenance-statements
      #   if: ${{ !inputs.skipPublishing }}
      #   run: |
      #     npm config set provenance true
      #     echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      #     echo "npmAlwaysAuth:true\n npmAuthToken: '$NPM_TOKEN'\n" >> ~/.yarnrc
      #     (cd packages/core && yarn workspaces foreach -Rt npm publish --tolerate-republish --tag $NPM_TAG)
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: 上传二进制到 gh release
      #   if: ${{ !inputs.skipPublishing }}
      #   shell: bash
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     RELEASE_VERSION: "v${{ inputs.version }}"
      #   run: |
      #     chmod +x ./.github/scripts/cli_upload_gh_release.sh
      #     ./.github/scripts/cli_upload_gh_release.sh
      #       - name: 开始发布

      - name: 通过 Action 上传二进制到 gh release
        uses: softprops/action-gh-release@v1
        # 403 错误 设置 Action 权限 github -> setting -> actiong -> general -> Workflow permissions
        with:
          generate_release_notes: true
          tag_name: ${{ github.repository }}
          body: ${{ github.event.head_commit.message }}
          token: ${{ github.token }}
          files: |
            ./packages/artifacts/*
