name: "构建 Cargo 包"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_RELEASE_LTO: "fat"
  GIT_AUTHOR_NAME: "SWC Bot"
  GIT_AUTHOR_EMAIL: "bot@swc.rs"
  GIT_COMMITTER_NAME: "SWC Bot"
  GIT_COMMITTER_EMAIL: "bot@swc.rs"

permissions:
  contents: write
  id-token: write

on:
  # 工作流的执行依赖其他 workflow 的调用
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      version:
        type: string
        required: true
      buildCli:
        type: boolean
        required: true
      skipBuild:
        type: boolean
        required: true
      skipPublishing:
        type: boolean
        required: true
      profile:
        type: string
        required: false
        default: release

jobs:
  check-if-build-required:
    name: 是否需要构建
    runs-on: ubuntu-latest
    outputs:
      need-build: ${{ steps.check.outputs.need-build }}
    steps:
      - uses: actions/checkout@v4
      # TODO: 检查是否存在 artifacts
      - id: check
        if: ${{ !inputs.skipBuild }}
        run: |
          echo "need-build=true" >> $GITHUB_OUTPUT

  build-node:
    if: needs.check-if-build-required.outputs.need-build == 'true'
    needs:
      - check-if-build-required
      # - create-git-tag-commit
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin

          - host: macos-latest
            target: aarch64-apple-darwin
            pre: |
              sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*;
              export CC=$(xcrun -f clang);
              export CXX=$(xcrun -f clang++);
              SYSROOT=$(xcrun --sdk macosx --show-sdk-path);
              export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT";

          - host: windows-latest
            target: x86_64-pc-windows-msvc

          - host: windows-latest
            target: i686-pc-windows-msvc

          - host: windows-latest
            target: aarch64-pc-windows-msvc

          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian

          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine

          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64

          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine

          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            setup: |
              sudo apt-get update
              sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y

    name: "构建 Node Native ${{ inputs.package }} - ${{ matrix.settings.target }} - node@20"
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
        # 引用 git tag 版本
        # with:
        #   ref: "v${{ inputs.version }}"
      - name: 构建 Napi
        uses: ./.github/actions/rust-build
        with:
          isNeedNode: true
          name: bindings-${{ matrix.settings.target }}-node
          path: |
            ./bindings/binding_compress_node/image-compress*
            ./bindings/binding_explore_node/explore*
          target: ${{ matrix.settings.target }}
          image: ${{ matrix.settings.docker }}
          pre: ${{ matrix.settings.setup }}
          build: |
            ${{ matrix.settings.pre }}
            pnpm build:node --target ${{ matrix.settings.target }}
            ${{ matrix.settings.post }}

            if [[ '${{ matrix.settings.target }}' == "x86_64-apple-darwin" ]]; then
              strip -x ./bindings/binding_compress_node/*.node
              strip -x ./bindings/binding_explore_node/*.node
            fi

  build-wasm:
    runs-on: ubuntu-latest
    name: "构建 Wasm ${{ inputs.package }}"
    strategy:
      fail-fast: false
      matrix:
        settings:
          - target: nodejs
            out: "pkg"

          - target: web
            out: "pkg"

          - target: bundler
            out: "pkg"

          - target: esm
            out: "esm"
    steps:
      - uses: actions/checkout@v4

      - name: 构建 WASM
        uses: ./.github/actions/rust-build
        with:
          isNeedNode: true
          name: bindings-${{ matrix.settings.target }}-wasm
          path: |
            ./bindings/binding_compress_wasm/dist/*.wasm
          build: |
            wasm-pack build ./bindings/binding_compress_wasm --out-name wasm --release --target ${{ matrix.settings.target }}

  publish:
    needs: build-node
    name: 发布 ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        # ref: "v${{ inputs.version }}"

      - uses: ./.github/actions/setup-node

      - name: 设置 npm 发行版标签
        run: |
          if [[ '${{ inputs.version }}' != *"nightly"* ]]; then
            echo "NPM_TAG=latest" >> $GITHUB_ENV
          else
            echo "NPM_TAG=nightly" >> $GITHUB_ENV
          fi

      - name: 安装依赖
        run: corepack enable && pnpm install

      - name: 下载所有 artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./packages/artifacts

      - name: 展示 artifacts 文件
        run: ls -R ./packages/artifacts
        shell: bash

      - name: 重命名 artifacts 文件
        run: |
          cp -r -v ./packages/artifacts/**/**/*.node ./packages/artifacts
          cp -r -v ./packages/artifacts/**/**/**/*.wasm ./packages/artifacts
        shell: bash

      #     - name: 移动 artifacts 文件
      #       shell: bash
      #       working-directory: .
      #       run: |
      #         chmod +x ./.github/scripts/cli_artifacts_rename.sh
      #         ./.github/scripts/cli_artifacts_rename.sh

      # - name: 设置 npm 包依赖
      #   shell: bash
      #   run: |
      #     node ./scripts/update_fallback_dependencies.js

      # - name: 发布 npm 包及长传 .node 文件到 github release
      # npm config set provenance true 命令设置发布 npm 包时候自动发布 github release https://docs.npmjs.com/generating-provenance-statements
      #   if: ${{ !inputs.skipPublishing }}
      #   run: |
      #     npm config set provenance true
      #     echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      #     echo "npmAlwaysAuth:true\n npmAuthToken: '$NPM_TOKEN'\n" >> ~/.yarnrc
      #     (cd packages/core && yarn workspaces foreach -Rt npm publish --tolerate-republish --tag $NPM_TAG)
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: 上传二进制到 gh release
      #   if: ${{ !inputs.skipPublishing }}
      #   shell: bash
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     RELEASE_VERSION: "v${{ inputs.version }}"
      #   run: |
      #     chmod +x ./.github/scripts/cli_upload_gh_release.sh
      #     ./.github/scripts/cli_upload_gh_release.sh
      #       - name: 开始发布

      - name: 通过 Action 上传二进制到 gh release
        uses: softprops/action-gh-release@v1
        # 403 错误 设置 Action 权限 github -> setting -> actiong -> general -> Workflow permissions
        with:
          generate_release_notes: true
          tag_name: ${{ github.repository }}
          body: ${{ github.event.head_commit.message }}
          token: ${{ github.token }}
          files: |
            ./packages/artifacts/*
